from __future__ import annotations

from typing import Any
from core.agent_base import BaseAgent
from core.protocol import ProjectBlueprint


class ScribeAgent(BaseAgent):
    def execute(self, input_data: Any) -> str:
        blueprint: ProjectBlueprint = input_data
        self.log("Writing README.md")

        fragments = "\n".join([f"- `{f.id}`: {f.description}" for f in blueprint.logic_fragments])
        state = "\n".join([f"- `{s.name}` ({s.type}): {s.description}" for s in blueprint.global_state])

        return f"""# {blueprint.app_name}

Generated by **ASET (MVP)**.

## Global State
{state or "- (none)"}

## Logic Fragments
{fragments or "- (none)"}

## Run
```bash
pip install -r requirements.txt
streamlit run app.py

`aset/agents/__init__.py`
```python
# Workforce package
"""