from __future__ import annotations

from typing import Any

from core.agent_base import BaseAgent
from core.protocol import ProjectBlueprint


class UIComposerAgent(BaseAgent):
    """
    Generates a stable, canonical Streamlit app that calls the canonical fragments:
      - initialize_state
      - render_sidebar_controls
      - load_prices
      - render_main_dashboard
    """

    def execute(self, input_data: Any) -> str:
        blueprint: ProjectBlueprint = input_data
        self.log("Composing Streamlit UI (app.py) from canonical blueprint")

        return f'''import streamlit as st

from logic import (
    initialize_state,
    render_sidebar_controls,
    load_prices,
    render_main_dashboard,
)

st.set_page_config(page_title="{blueprint.app_name}", layout="wide")

st.title("{blueprint.app_name}")
st.caption("Generated by ASET")

# ---- Initialize state ----
init_out = initialize_state()
for k, v in init_out.items():
    if k not in st.session_state:
        st.session_state[k] = v

# ---- Sidebar controls ----
sidebar_out = render_sidebar_controls(
    st.session_state.get("tickers", []),
    st.session_state.get("period", "6mo"),
)
for k, v in sidebar_out.items():
    st.session_state[k] = v

tickers = st.session_state.get("tickers", [])
period = st.session_state.get("period", "6mo")

# ---- Load prices ----
status_message = st.session_state.get("status_message", "")
if tickers:
    price_out = load_prices(tickers, period)
    if "price_data" in price_out:
        st.session_state["price_data"] = price_out["price_data"]
    if "status_message" in price_out:
        status_message = price_out["status_message"]
        st.session_state["status_message"] = status_message
else:
    st.session_state["price_data"] = None
    status_message = "Add at least one ticker in the sidebar."
    st.session_state["status_message"] = status_message

# ---- Main dashboard ----
render_main_dashboard(
    st.session_state.get("tickers", []),
    st.session_state.get("price_data"),
    st.session_state.get("status_message", ""),
)
'''
